services:
  
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: services/Gateway
      dockerfile: Dockerfile
    depends_on:
      - identity
      - messages.commands
  
  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: services/Identity/Identity.Web/Dockerfile
    depends_on:
      - postgres
    
  postgres:
    image: postgres:latest
    
  dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest