services:
  
  gateway:
    ports:
      - "8080:80"
    
  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=Identity;UserName=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Issuer=${JWT_ISSUER}
      - OTEL_EXPORTER_OTLP_ENDPOINT
    ports:
      - "23450:8080"

  messages.commands:
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=Messages;UserName=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Issuer=${JWT_ISSUER}
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__User=${RABBITMQ_USER}
      - RabbitMQ__Pass=${RABBITMQ_PASS}
    ports:
      - "23452:8080"
      
  messages.queries:
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__Database=Server=mssql;Database=Messages;User Id=SA; Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis;
      - Jwt__Key=${JWT_KEY}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Issuer=${JWT_ISSUER}
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__User=${RABBITMQ_USER}
      - RabbitMQ__Pass=${RABBITMQ_PASS}
    ports:
      - "23451:8080"
  
  messages.hub:
    environment:
      - ASPNETCORE_ENVIRONMENT
      - Jwt__Key=${JWT_KEY}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Issuer=${JWT_ISSUER}
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__User=${RABBITMQ_USER}
      - RabbitMQ__Pass=${RABBITMQ_PASS}
    ports:
      - "23454:8080"
  
  postgres:
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    ports:
      - "5432:5432"

  mssql:
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD
    ports:
      - "1433:1433"

  rabbitmq:
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  dashboard:
    ports:
      - "18888:18888"
      - "4317:18889"
  
  redis:
    ports:
      - "6379:6379"